[tools]
claude = "latest"
codex = "latest"
dotnet = ["latest", "8"]
java = "latest"
node = "latest"
opencode = "latest"
pnpm = "latest"

# WSL-only because apt nvim is not up to date with latest - instead we use mise
neovim = "latest"
